version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3210:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
